iris/home/urls.py
from django.urls import path
from . import views


app_name = 'home'

urlpatterns = [
    path('', views.index, name='home_page'),
]

iris/iris/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('predict/', include('predict.urls', namespace='predict')),   # 02
    path('train/', include('train.urls', namespace='train'))
]

iris/predict/urls.py
from django.urls import path
from . import views

app_name = 'predict'

urlpatterns = [
    path('', views.predict, name='predict_page'),
    path('submit/', views.predict_chances, name='submit_prediction'),
    path('results/', views.view_results, name='results'),
]

iris/train/urls.py
from django.urls import path
from . import views

app_name = 'train'

urlpatterns = [
    path('', views.train, name='train_page'),
    path('train/', views.train_svc, name='submit_training'),
    path('models/', views.view_models, name='models'),
]

iris/home/models.py
from django.db import models

# Create your models here.

iris/predict/models.py
from django.db import models


# Create your models here.
class PredResult(models.Model):

    sepal_length = models.FloatField()
    sepal_width = models.FloatField()
    petal_length = models.FloatField()
    petal_width = models.FloatField()
    classification = models.CharField(max_length=30)

    def __str__(self):
        return self.classification

iris/train/models.py
from django.db import models


# Create your models here.
class TrainResult(models.Model):

    model_name = models.CharField(max_length=30)
    hp_c = models.FloatField(default=1e-3)
    train_score = models.FloatField()
    test_score = models.FloatField()
    train_date = models.DateTimeField('date trained')

    def __str__(self):
        return f"{self.model_name} with {self.test_score} accuracy"

iris/home/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def index(request):
    #return HttpResponse("首页")
    return render(request, 'home/index.html')

iris/predict/views.py
import os
import pandas as pd

from .models import PredResult
from django.http import JsonResponse
from django.shortcuts import render


# Create your views here.
def predict(request):
    return render(request, 'predict/index.html')


def predict_chances(request):    # 4

    if request.POST.get('action') == 'post':

        # Receive data from client
        sepal_length = float(request.POST.get('sepal_length'))
        sepal_width = float(request.POST.get('sepal_width'))
        petal_length = float(request.POST.get('petal_length'))
        petal_width = float(request.POST.get('petal_width'))

        # Unpickle the model
        path = os.path.abspath('') + '\\model\\svc.pickle'
        #model = pd.read_pickle(r'.\model\svc.pickle')
        model = pd.read_pickle(path)
        # Make prediction
        result = model.predict(
            [[sepal_length, sepal_width, petal_length, petal_width]]
        )
        # Write into database
        PredResult.objects.create(
            sepal_length=sepal_length,
            sepal_width=sepal_width,
            petal_length=petal_length,
            petal_width=petal_width,
            classification=result[0]
        )
        # Return for JavaScript
        return JsonResponse(
            {
                'result': result[0],
                'sepal_length': sepal_length,
                'sepal_width': sepal_width,
                'petal_length': petal_length,
                'petal_width': petal_width
             },
            safe=False
        )


def view_results(request):
    # Submit prediction and show all
    data = {"dataset": PredResult.objects.all()}
    return render(request, 'predict/results.html', data)

iris/train/views.py
import os
import pandas as pd
import numpy as np
import seaborn as sns

from django.utils import timezone
from django.http import JsonResponse
from django.shortcuts import render

from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix

from .models import TrainResult


# Create your views here.
def train(request):
    return render(request, 'train/index.html')

def train_svc(request):

    # Receive data from client
    hp_c = float(request.POST.get('hp_c'))

    # Load dataset
    csv_path = os.path.abspath('') + '\\train\\data\\iris.csv'
    #df = pd.read_csv(r"../data/iris.csv")
    df = pd.read_csv(csv_path)
    # Split into feature and label
    X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
    y = df['classification']
    # Split train test datasets
    x_train, x_test, y_train, y_test = train_test_split(
        X, y, test_size=0.20, random_state=1
    )
    # Train and evaluate the model
    model = SVC(C=hp_c).fit(x_train.values, y_train.values)
    score_train = np.mean(cross_val_score(model, x_train.values, y_train.values, cv=5))
    score_test = model.score(x_test.values, y_test)
    conf_matrix = confusion_matrix(y_test, model.predict(x_test.values))
    # Pickle the model
    mod_path = os.path.abspath('') + '\\model\\svc.pickle'
    pd.to_pickle(model, mod_path)

    # Save confusion matrix as heatmap
    df_cm = pd.DataFrame(
        conf_matrix,
        index=[
            'Iris-setosa',
            'Iris-versicolor',
            'Iris-virginica'
        ],
        columns=[
            'Iris-setosa',
            'Iris-versicolor',
            'Iris-virginica'
        ]
    )
    '''
    fig = sns.heatmap(
        df_cm,
        cmap='Blues',
        square=True, linewidths=1,
        linecolor='black',
        annot=True
    )
    img = fig.get_figure()
    fig_path = os.path.abspath('') + '\\static\\images\\cm'
    img.savefig(fig_path, dpi=400)
    '''

    # Write into database
    TrainResult.objects.create(
        model_name='SCV',
        hp_c=hp_c,
        train_score=score_train,
        test_score=score_test,
        train_date=timezone.now()
    )

    return JsonResponse(
        {
            'hp_c': hp_c,
            'train_score': score_train,
            'test_score': score_test,
        },
        safe=False
    )


def view_models(request):
    # Submit training and show all
    data = {"dataset": TrainResult.objects.all()}
    return render(request, "train/models.html", data)

iris/home/templates/home/index.html
{% extends "base.html" %}

{% block main %}
This is home page.
{% endblock %}

iris/predict/templates/predict/index.html
{% extends "base.html" %}

{% block main %}
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Prediction Results</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5 class="pt-3">Prediction Input:</h5>
                <div>Sepal Length: <span id="sl"></span></div>
                <div>Sepal Width: <span id="sw"></span></div>
                <div>Petal Length: <span id="pl"></span></div>
                <div>Petal width: <span id="pw"></span></div>
                <h5 class="pt-3">Prediction Classification:</h5>
                <div id="prediction"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="/predict/results" role="button">View DB</a>
            </div>
        </div>
    </div>
</div>

<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            <h1>Iris Prediction</h1>
            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="sepal_length">Sepal Length</label>
                    <input type="number" step="0.1" class="form-control" id="sepal_length" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="sepal_width">Sepal Width</label>
                    <input type="number" step="0.1" class="form-control" id="sepal_width" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="petal_length">Petal Length</label>
                    <input type="number" step="0.1" class="form-control" id="petal_length" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="petal_width">Petal Width</label>
                    <input type="number" step="0.1" class="form-control" id="petal_width" placeholder="" required>
                </div>
                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Submit</button>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "predict:submit_prediction" %}',
            data:{
                sepal_length:$('#sepal_length').val(),
                sepal_width:$('#sepal_width').val(),
                petal_length:$('#petal_length').val(),
                petal_width:$('#petal_width').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"].reset();
                document.getElementById("prediction").innerHTML = json['result']
                document.getElementById("sl").innerHTML = json['sepal_length']
                document.getElementById("sw").innerHTML = json['sepal_width']
                document.getElementById("pl").innerHTML = json['petal_length']
                document.getElementById("pw").innerHTML = json['petal_width']
            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script>

{% endblock %}

iris/predict/templates/predict/results.html
{% extends "base.html" %}

{% block main %}
    <div class="container pt-5">
        <div class="row">

        <h1>Prediction Results</h1>

            <table class="table">
                <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Sepal length</th>
                <th scope="col">Sepal width</th>
                <th scope="col">Petal length</th>
                <th scope="col">Petal width</th>
                <th scope="col">Prediction</th>
                <th scope="col">Verification</th>
                </tr>
                </thead>
                <tbody>
                {% for data in dataset %}
                    <tr>
                    <th scope="row">{{ data.id }}</th>
                    <td>{{ data.sepal_length }}</td>
                    <td>{{ data.sepal_width }}</td>
                    <td>{{ data.petal_length }}</td>
                    <td>{{ data.petal_width }}</td>
                    <td>{{ data.classification }}</td>
                    <td>{{ 1 }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

iris/templates/base.html
<!doctype html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>Iris prediction</title>
    </head>
    <body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/predict">Predict</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/predict/results">DB</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/train">Train</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/train/models">Models</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block main %}
    {% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

iris/train/templates/train/index.html
{% extends "base.html" %}

{% block main %}
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Training Result</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5 class="pt-3">Hyperparameters:</h5>
                <div>C: <span id="hpc"></span></div>
                <h5 class="pt-3">Model Performance:</h5>
                <div>Train Score: <span id="trs"></span></div>
                <div>Test Score: <span id="tes"></span></div>
                <h5 class="pt-3">Confusion Matrix:</h5>
                {% load static %}
                <img src="/images/cm.png" alt="confusion matrix" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="/train/models" role="button">View Models</a>
            </div>
        </div>
    </div>
</div>

<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            <h1>Train a new SVC</h1>
            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="hp_c">C</label>
                    <input type="number" step="0.1" class="form-control" id="hp_c" placeholder="" required>
                </div>
                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Train</button>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).on('submit', '#post-form', function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "train:submit_training" %}',
            data:{
                hp_c:$('#hp_c').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"].reset();
                document.getElementById("hpc").innerHTML = json['hp_c']
                document.getElementById("trs").innerHTML = json['train_score']
                document.getElementById("tes").innerHTML = json['test_score']
            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script>
{% endblock %}

iris/train/templates/train/models.html
{% extends "base.html" %}

{% block main %}
    <div class="container pt-5">
        <div class="row">

        <h1>Trained Models</h1>

            <table class="table">
                <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">C</th>
                <th scope="col">Train Score</th>
                <th scope="col">Test Score</th>
                <th scope="col">Date Trained</th>
                </tr>
                </thead>
                <tbody>
                {% for data in dataset %}
                    <tr>
                    <th scope="row">{{ data.id }}</th>
                    <td>{{ data.model_name }}</td>
                    <td>{{ data.hp_c }}</td>
                    <td>{{ data.train_score }}</td>
                    <td>{{ data.test_score }}</td>
                    <td>{{ data.train_date }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}